# name: openAFRICA upload

# on:
#   push:
#     branches: [ master ]
#     paths:
#       - "data/**"

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies

#       run: |
#         cd scripts
#         pip install pipenv
#         pipenv install
#     - name: upload to openAFRICA
#       env:
#         CKAN_API_KEY: ${{secrets.CKAN_API_KEY}}
#       run: |
#         cd scripts
#         ./upload_mbtiles.sh
